# Generated by Django 5.1.2 on 2024-11-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ubicacion', models.CharField(max_length=50)),
                ('tipo_servicio', models.CharField(max_length=10)),
                ('menu', models.CharField(max_length=500)),
                ('capacidad', models.IntegerField()),
                ('infraestructura', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=500)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idadmin', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.AutoField(primary_key=True, serialize=False)),
                ('pago_total', models.DecimalField(decimal_places=2, max_digits=30)),
                ('fecha', models.DateField()),
                ('estado_pago', models.CharField(max_length=20)),
                ('metodo_de_pago', models.CharField(max_length=20)),
                ('cantidad_personas', models.IntegerField()),
                ('idservicio', models.IntegerField()),
                ('idcliente', models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
    ]
