# Generated by Django 5.1.2 on 2024-11-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='personal',
            name='password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='menu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
